# Generated by Django 3.1.9 on 2022-04-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalSessionAD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_full_name', models.CharField(blank=True, max_length=10, unique=True)),
                ('session_short_name', models.CharField(blank=True, max_length=5, unique=True)),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalSessionBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_full_name', models.CharField(blank=True, max_length=10, unique=True)),
                ('session_short_name', models.CharField(blank=True, max_length=5, unique=True)),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('print_no', models.CharField(blank=True, max_length=10)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHERS')], help_text='1=MALE,2=FEMALE,3=OTHERS')),
                ('created_date_ad', models.DateTimeField()),
                ('created_date_bs', models.CharField(max_length=15)),
            ],
        ),
    ]
