# Generated by Django 3.1.9 on 2022-04-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220410_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch'),
        ),
    ]
