# Generated by Django 3.1.9 on 2022-05-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_print_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='short_name',
            new_name='code',
        ),
    ]
