# Generated by Django 3.1.9 on 2022-05-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220505_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='gender',
        ),
    ]
