# Generated by Django 3.1.9 on 2022-08-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220807_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='owner_photo',
            field=models.ImageField(default='', upload_to='print/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='print',
            name='qr',
            field=models.ImageField(default='', upload_to='print/'),
            preserve_default=False,
        ),
    ]
