# Generated by Django 3.1.9 on 2022-08-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220807_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='print_no',
        ),
        migrations.AddField(
            model_name='print',
            name='card_type',
            field=models.CharField(choices=[('1', 'DEBIT'), ('2', 'CREDIT')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
