# Generated by Django 3.1.9 on 2022-08-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220815_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='address_nepali',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='print',
            name='citizenship_no_nepali',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='print',
            name='first_name_nepali',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='print',
            name='last_name_nepali',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='print',
            name='middle_name_nepali',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='print',
            name='mobile_no_nepali',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
