# Generated by Django 3.1.9 on 2022-08-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220816_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='name_nepali',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
