# Generated by Django 3.1.9 on 2022-08-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220815_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'STAFF'), (3, 'MAINTAINER')], default=1, max_length=1),
        ),
    ]
